#------------------------------------------------------------------#
# DEFINEFLAGS                                                      #
#------------------------------------------------------------------#

# B01, B20, B50, B100
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS

# B320
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DAHFshellshape

# Box20b
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DBYTESWAP

# HaloesGoingMAD
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES

# SubhaloesGoingNotts (A1-A3, A4-5)
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DAHFrfocus -DDOUBLE
#DEFINEFLAGS	=	-DMULTIMASS #-DAHFnewCloseRefDist

# Box160, MW1.512
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES

# LGR2Mpc, ... (basically any GADGET output produced by Gustavo!)
#------------------------------------------------------------------
#DEFINEFLAGS    =      -DMULTIMASS -DGAS_PARTICLES -DMETALHACK #-DAHFdisks #-DAHFnewHaloIDs #-DAHFexciseSubhaloStars #-DAHFbinary

# CLUES-gasblobs
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DAHFptfocus=0 -DAHFnoremunbound -DDVIR_200RHOCRIT -DMANUAL_DVIR=200

# MW1.1024g1bwk, g1536, g15784, GALFOBS
#------------------------------------------------------------------
#DEFINEFLAGS    =      -DMULTIMASS -DGAS_PARTICLES -DBYTESWAP

# LTBvoids
#------------------------------------------------------------------
#DEFINEFLAGS    =      -DAHFrfocus -DDVIR_200RHOCRIT

# GHALO
#------------------------------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS -DTIPSY_ZOOMDATA -DGAS_PARTICLES
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DBYTESWAP

# d2100
#-------
#DEFINEFLAGS	=	-DMULTIMASS -DGAS_PARTICLES -DBYTESWAP

# simuCroCo tests
#-----------------
#DEFINEFLAGS	=	-DGADGET 

# sigmaH flags for Jubilee H0voids project
#------------------------------------------
#DEFINEFLAGS	=	-DMULTIMASS

# DPhalos
#---------
#DEFINEFLAGS	=	-DDPhalos
#DEFINEFLAGS	=	-DGADGET

# Sussing Merger Trees
#======================
#DEFINEFLAGS	=	-DSUSSING2013

# AHF2
#======
#DEFINEFLAGS	+=	-DVERBOSE -DVERBOSE2 -DPATCH_DEBUG -DDEBUG_AHF2 -DAHFgridtreefile -DAHFwritePreliminaryHalos
#DEFINEFLAGS	+=	-DCUBEKEY_128 //Defined by default in define.h



#------------------------------------------------------------------#
# Set environment for the system                                   #
#------------------------------------------------------------------#

CC         	=	mpicc -std=c99 -Wall -W
FC         	=	mpif90
OPTIMIZE	=	-O2
CCFLAGS		=
LNFLAGS		=
DEFINEFLAGS	+=	-DWITH_MPI
MAKE		=	make
