##########################
###Compilers and paths####
##########################

EXEC = Inspector_Gadget_Q

GCCC = /bgsys/drivers/ppcfloor/comm/gcc/bin/mpicc  # Blue Gene/Q GNU cross-compiler alias

FFTW3_INCL = -I/bgsys/home1/slatest_a-g/fftw332dp-fenq-gnucompiler/fftw-3.3.2/include  # FFTW3 for NYBlue/Q
FFTW3LIB = -L/bgsys/home1/slatest_a-g/fftw332dp-fenq-gnucompiler/fftw-3.3.2/lib -lfftw3  # FFTW3 for NYBlue/Q
CFITSIO_INCL = -I/bgsys/home1/slatest_a-g/cfitsio-fenq-gnucompiler/cfitsio/include
CFITSIOLIB = -L/bgsys/home1/slatest_a-g/cfitsio-fenq-gnucompiler/cfitsio/lib -lcfitsio
MPICHLIB = 
OMPFLAG = -DHAVE_OpenMP -fopenmp
CFLAGS = -O3 -Wall $(OMPFLAG) -I. $(FFTW3_INCL) $(CFITSIO_INCL) -lm 