##########################
###Compilers and paths####
##########################

EXEC = Inspector_Gadget_Stampede

GCCC = mpicc
FFTW3_INCL = -I${TACC_FFTW3_INC}
FFTW3LIB = -Wl,-rpath,${TACC_FFTW3_LIB}  -L${TACC_FFTW3_LIB} -lfftw3
CFITSIO_INCL = -I/home1/02918/apetri/misc/cfitsio/include
CFITSIOLIB = -L/home1/02918/apetri/misc/cfitsio/lib -lcfitsio
OMPFLAG = -DHAVE_OpenMP -openmp
CFLAGS = -O3 -Wall $(OMPFLAG) -I. $(FFTW3_INCL) $(CFITSIO_INCL)

PYTHON = python